### ISSUE TITLE
Talk at Rust NYC

### ISSUE THREAD

**Issue by rbalicki2** [gregkatz/cvsolitaire#6]
Hi Greg,
I did a very cursory Google search, couldn't find contact info for you. I am the organizer of the Rust NYC Meetup group. Would you like to speak at an upcoming meetup? Send me an email at robert.balicki@gmail.com if you're interested! TBH I'd personally love to learn about how to integrate Rust with Emscripten. The tutorials I tried to use a few months ago were pretty bare bones and I'm sure there'd be a lot of interest.

Best,
Robert

**Comment by gregkatz** [comment]
Hey, sorry about the limited internet presence. I'll shoot you an email to discuss further!
